# Generated by Django 4.0.8 on 2023-01-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bocy',
            new_name='body',
        ),
    ]
